// front/src/pages/LettersPage.vue
<script setup>
import { onMounted, onUnmounted, ref } from "vue";
import { useRouter } from "vue-router";
import { getLetters } from "../api";
import { LETTERS } from "../data/letterCatalog";

const router = useRouter();

const letters = ref(LETTERS.map((item) => ({ ...item, enabled: false })));
const loading = ref(true);
const error = ref("");
const notice = ref("");

let noticeTimeoutId = null;
let active = true;

function showSoonMessage() {
  notice.value = "곧 열려요";
  if (noticeTimeoutId) {
    window.clearTimeout(noticeTimeoutId);
  }
  noticeTimeoutId = window.setTimeout(() => {
    notice.value = "";
  }, 1400);
}

function handleLetterClick(letter) {
  if (letter.enabled) {
    router.push(`/learn/${letter.key}`);
    return;
  }
  showSoonMessage();
}

async function loadLetters() {
  loading.value = true;
  error.value = "";

  try {
    const items = await getLetters();
    if (active) {
      letters.value = items;
    }
  } catch (loadError) {
    if (active) {
      error.value = "글자 목록을 불러오지 못했어요.";
      letters.value = LETTERS.map((item) => ({ ...item, enabled: false }));
    }
  } finally {
    if (active) {
      loading.value = false;
    }
  }
}

onMounted(() => {
  active = true;
  loadLetters();
});

onUnmounted(() => {
  active = false;
  if (noticeTimeoutId) {
    window.clearTimeout(noticeTimeoutId);
  }
});
</script>

<template>
  <main class="page letters-page">
    <header class="top-nav">
      <button type="button" class="btn ghost" @click="router.push('/library')">
        뒤로
      </button>
      <button type="button" class="btn ghost" @click="router.push('/')">
        홈
      </button>
    </header>

    <section class="panel letters-panel">
      <h1 class="section-title">어떤 글자를 배울까?</h1>
      <p class="section-subtitle">가~하 중에서 골라요.</p>

      <p v-if="loading" class="status-text">글자를 불러오는 중...</p>
      <p v-if="error" class="status-text warning">{{ error }}</p>

      <div class="letters-grid">
        <button
          v-for="letter in letters"
          :key="letter.key"
          type="button"
          :class="['letter-btn', letter.enabled ? 'enabled' : 'locked']"
          @click="handleLetterClick(letter)"
          :aria-disabled="!letter.enabled"
        >
          {{ letter.label }}
        </button>
      </div>

      <p class="soon-message" aria-live="polite">
        {{ notice }}
      </p>
    </section>
  </main>
</template>

// frontend/src/pages/LettersPage.jsx
import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getLetters } from "../api";
import { LETTERS } from "../data/letterCatalog";

function LettersPage() {
  const navigate = useNavigate();
  const [letters, setLetters] = useState(
    LETTERS.map((item) => ({ ...item, enabled: false }))
  );
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const noticeTimeoutRef = useRef(null);

  useEffect(() => {
    let active = true;

    async function loadLetters() {
      setLoading(true);
      setError("");

      try {
        const items = await getLetters();
        if (active) {
          setLetters(items);
        }
      } catch (loadError) {
        if (active) {
          setError("글자 목록을 불러오지 못했어요.");
          setLetters(LETTERS.map((item) => ({ ...item, enabled: false })));
        }
      } finally {
        if (active) {
          setLoading(false);
        }
      }
    }

    loadLetters();

    return () => {
      active = false;
      if (noticeTimeoutRef.current) {
        window.clearTimeout(noticeTimeoutRef.current);
      }
    };
  }, []);

  function showSoonMessage() {
    setNotice("곧 열려요");
    if (noticeTimeoutRef.current) {
      window.clearTimeout(noticeTimeoutRef.current);
    }
    noticeTimeoutRef.current = window.setTimeout(() => {
      setNotice("");
    }, 1400);
  }

  function handleLetterClick(letter) {
    if (letter.enabled) {
      navigate(`/learn/${letter.key}`);
      return;
    }
    showSoonMessage();
  }

  return (
    <main className="page letters-page">
      <header className="top-nav">
        <button type="button" className="btn ghost" onClick={() => navigate("/library")}>
          뒤로
        </button>
        <button type="button" className="btn ghost" onClick={() => navigate("/")}>
          홈
        </button>
      </header>

      <section className="panel letters-panel">
        <h1 className="section-title">어떤 글자를 배울까?</h1>
        <p className="section-subtitle">가~하 중에서 골라요.</p>

        {loading ? <p className="status-text">글자를 불러오는 중...</p> : null}
        {error ? <p className="status-text warning">{error}</p> : null}

        <div className="letters-grid">
          {letters.map((letter) => (
            <button
              key={letter.key}
              type="button"
              className={`letter-btn ${letter.enabled ? "enabled" : "locked"}`}
              onClick={() => handleLetterClick(letter)}
              aria-disabled={!letter.enabled}
            >
              {letter.label}
            </button>
          ))}
        </div>

        <p className="soon-message" aria-live="polite">
          {notice}
        </p>
      </section>
    </main>
  );
}

export default LettersPage;
