// front/src/pages/LibraryPage.vue
<script setup>
import { useRouter } from "vue-router";

const router = useRouter();
</script>

<template>
  <main class="page library-page">
    <header class="top-nav">
      <button type="button" class="btn ghost" @click="router.push('/')">
        홈
      </button>
    </header>

    <section class="panel library-panel">
      <h1 class="section-title">책장을 열어볼까?</h1>
      <p class="section-subtitle">오늘은 가나다 한글 책 한 권!</p>

      <button
        type="button"
        class="book-card"
        @click="router.push('/letters')"
        aria-label="가나다 한글 책 열기"
      >
        <span class="book-spine">가나다</span>
        <span class="book-title">가나다 한글</span>
        <span class="book-hint">터치해서 시작</span>
      </button>
    </section>
  </main>
</template>

// frontend/src/pages/LibraryPage.jsx
import { useNavigate } from "react-router-dom";

function LibraryPage() {
  const navigate = useNavigate();

  return (
    <main className="page library-page">
      <header className="top-nav">
        <button type="button" className="btn ghost" onClick={() => navigate("/")}>
          홈
        </button>
      </header>

      <section className="panel library-panel">
        <h1 className="section-title">책장을 열어볼까?</h1>
        <p className="section-subtitle">오늘은 가나다 한글 책 한 권!</p>

        <button
          type="button"
          className="book-card"
          onClick={() => navigate("/letters")}
          aria-label="가나다 한글 책 열기"
        >
          <span className="book-spine">가나다</span>
          <span className="book-title">가나다 한글</span>
          <span className="book-hint">터치해서 시작</span>
        </button>
      </section>
    </main>
  );
}

export default LibraryPage;
